#!/usr/bin/env python3

import pygame
import sys
from time import sleep


def dragonborn():
    pygame.init()

    width = 800
    height = 600
    speed = [5, 5]

    screen = pygame.display.set_mode((width, height))

    ball = pygame.image.load('dragonborn.png')
    ballrect = ball.get_rect()

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()

        ballrect = ballrect.move(speed)
        if ballrect.left < 0 or ballrect.right > width:
            speed[0] = -speed[0]
        if ballrect.top < 0 or ballrect.bottom > height:
            speed[1] = -speed[1]

        screen.fill((127, 127, 127))
        screen.blit(ball, ballrect)
        pygame.display.flip()


def main():
    pygame.init()
    W, H = 800, 600
    screen = pygame.display.set_mode((W, H))
    width, height = 500, 400
    rect = pygame.Rect((W - width)/2, (H - height)/2, width, height)

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()

        screen.fill((127, 127, 127))
        pygame.draw.rect(screen, (26, 161, 216), rect)
        pygame.display.flip()
        sleep(0.1)


if __name__ == '__main__':
    dragonborn()
