#!/usr/bin/env python3

import pygame


def main():
    pygame.init()

    width = 320
    height = 240
    speed = [2, 2]

    screen = pygame.display.set_mode((width, height))

    ball = pygame.image.load('ball.bmp')
    ballrect = ball.get_rect()

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT: sys.exit()

        ballrect = ballrect.move(speed)
        if ballrect.left < 0 or ballrect.right > width:
            speed[0] = -speed[0]
        if ballrect.top < 0 or ballrect.bottom > height:
            speed[1] = -speed[1]

        screen.fill((0, 0, 0))  # blacken
        screen.blit(ball, ballrect)
        pygame.display.flip()


if __name__ == '__main__':
    main()
